### ISSUE TITLE
[EPIC] Creare organizatie ONG

### ISSUE THREAD

**Issue by irina-adam** [peviitor-ro/community#17]
- [x] rezervare nume
- [x] creare statut
- [x] declaratie membrilor
- [x] deschidere cont trezorerie

**Comment by irina-adam** [comment]
Trebuie refacute urmatoarele: 
- [ ]  statut reactualizat cu art. 6 h) din OG nr. 26/2000
- [ ] refacere contract de comodat
- [ ] sa certifice pentru confromitate cu originalul copiile actelor de identitate, conform art. 7 lit. c) din OG nr. 26/2000
- [ ] depunere certificare de cazier fiscal
